### ISSUE TITLE
Type for the instance variable "authenticationChoice"

### ISSUE THREAD

**Issue by kozusznik** [fiji-hpc/scijava-parallel#29]
Use enumeration type(newly created) instead of String for the instance variable https://github.com/fiji-hpc/scijava-parallel/blob/de4a2efbb0c0da62be77f0c3b069b9284c10aeb5/src/main/java/cz/it4i/parallel/runners/HPCSettings.java#L26.

**Comment by velissarious** [comment]
I added new enum called AuthenticationChoice and replaced the old String authenticationChoice variables with new ones of type AuthenticationChoice. The only exception is the authenticationChoice variable/parameter in HPCSettingsGui which has to be String in order to be presented as a ChoiceWidget. However, the choice is converted to enum later.

**Comment by kozusznik** [comment]
That is OK

**Comment by kozusznik** [comment]
Ensure also correct running of legacy editor HPCSettingsGui.

**Comment by kozusznik** [comment]
Moved to https://redmine.it4i.cz/redmine/issues/1343
