### ISSUE TITLE
Edit newly created profile

### ISSUE THREAD

**Issue by kozusznik** [fiji-hpc/scijava-parallel#31]
avoid creation of non-initialized profile 
fix bug with empty ParadigmManager.

**Comment by velissarious** [comment]
Now the user has to edit the new profile before it is added and the settings are set null in case the user has not approved them by pressing OK or there were not old settings that had been once approved. If the settings are null the profile is not created.

The bug with the empty ParadigmManager is fixed, the problem was that the paradigm selection run on a different thread (the FX thread) which caused the ParadigmManager to not find a selection most of the time.
